name: Relay Stream
on:
  workflow_dispatch: {}

jobs:
  relay:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Stream videos in sequence
        env:
          RTMP_URL: ${{ secrets.RTMP_URL }}
        run: |
          set -x

          echo "=== Streaming : Opening Keynote ==="
          ffmpeg -re -ss 00:57:47 -to 03:02:39 -i "https://github.com/Natolix/yt-redif/releases/download/v1/RDC26.Opening.Keynote.4vxV5T8xTJw.webm" -c:v copy -c:a aac -ar 44100 -b:a 128k -f flv "$RTMP_URL"

          echo "=== Streaming : Creator Keynote ==="
          ffmpeg -re -ss 00:23:11 -to 01:39:28 -i "https://github.com/Natolix/yt-redif/releases/download/v1/RDC26.Creator.Keynote.mkv" -c:v copy -c:a aac -ar 44100 -b:a 128k -f flv "$RTMP_URL"

          echo "=== Streaming : Roblox Innovation Awards ==="
          ffmpeg -re -i "https://github.com/Natolix/yt-redif/releases/download/v1/Roblox.Innovation.Awards.coupee.mkv" -c:v copy -c:a aac -ar 44100 -b:a 128k -f flv "$RTMP_URL"

          exit 0
